### ISSUE TITLE
 cart template throws error

### ISSUE THREAD

**Issue by besrabasant** [roots/sage-woocommerce#3]
I am not able to make the `cart/cart.blade.php` work.  

it Throws error 

```
( ! ) Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function startSection() on null in 
```

**Comment by MWDelaney** [comment]
Can you show the content of your `cart.blade.php` here? It’s difficult to troubleshoot code we cannot see.

**Comment by besrabasant** [comment]
It's kind of strange... But even if I keep just

```
@extends('layouts.app')

@section('content')
@endsection
```

in the template file... It throws an error.


The only thing that works is if I keep the template file empty.

**Comment by MWDelaney** [comment]
Does it work if you use the full contents of the default PHP template from WooCommerce?

**Comment by mejta** [comment]
Hey, you should not use `@extends` and `@section` in this template. Have a look into the original template from WooCommerce plugin and if the original template doesn't contain `get_header` or `get_footer` function call, don't use `@extends` or `@section` in your template.

The cart template should look like this:

```php
@php
wc_print_notices();
do_action( 'woocommerce_before_cart' );
@endphp

<form class="woocommerce-cart-form" action="{{ wc_get_cart_url() }}" method="post">
  @php
  do_action( 'woocommerce_before_cart_table' );
  @endphp

	<table class="shop_table shop_table_responsive cart woocommerce-cart-form__contents" cellspacing="0">
		<thead>
			<tr>
				<th class="product-remove">&nbsp;</th>
				<th class="product-thumbnail">&nbsp;</th>
				<th class="product-name">{{ esc_html_e( 'Product', 'woocommerce' ) }}</th>
				<th class="product-price">{{ esc_html_e( 'Price', 'woocommerce' ) }}</th>
				<th class="product-quantity">{{ esc_html_e( 'Quantity', 'woocommerce' ) }}</th>
				<th class="product-subtotal">{{ esc_html_e( 'Total', 'woocommerce' ) }}</th>
			</tr>
		</thead>
		<tbody>
      @php
      do_action( 'woocommerce_before_cart_contents' );
      @endphp

			
      @foreach ( WC()->cart->get_cart() as $cart_item_key => $cart_item )
        @php
				$_product   = apply_filters( 'woocommerce_cart_item_product', $cart_item['data'], $cart_item, $cart_item_key );
        $product_id = apply_filters( 'woocommerce_cart_item_product_id', $cart_item['product_id'], $cart_item, $cart_item_key );
        @endphp

        ...

			@endforeach

      @php
      do_action( 'woocommerce_cart_contents' );
      @endphp

      ...

      @php
      do_action( 'woocommerce_after_cart_contents' );
      @endphp
		</tbody>
	</table>
  @php
  do_action( 'woocommerce_after_cart_table' );
  @endphp
</form>

<div class="cart-collaterals">
	@php
  do_action( 'woocommerce_cart_collaterals' );
	@endphp
</div>

@php
do_action( 'woocommerce_after_cart' );
@endphp
```

**Comment by mejta** [comment]
Basicaly only templates `archive-product.blade.php` and `single-product.blade.php` can contain `@extends` and `@section` directive.

Also be careful on function calls `wc_get_template( 'archive-product.php' )` in `taxonomy-product_cat.blade.php` and `taxonomy-product_tag.blade.php`. Replace that in your blade templates with `@include('woocommerce.archive-product')`.

**Comment by mejta** [comment]
Also, there is a bug that there is no `$__env` variable set in blade templates that prevents usage of `@foreach` too, so, for now, you can use:

```
@php
foreach(...):
@endphp
 ...
@php
endforeach;
@endphp

I will investigate this bug further and update the repository.

**Comment by mejta** [comment]
Ok, investigation done. If you append following code at the beginning of the `.blade.php` file, everything will work.

```php
@php
$__env = App\sage('blade');
@endphp
```

**Comment by besrabasant** [comment]
like every `.blade.php` or just the **woocommerce** templates.

**Comment by besrabasant** [comment]
strange... now `cart.blade.php` is not working... I mean it's not being included in the templates... instead, the default is rendered.

**Comment by besrabasant** [comment]
Now it's working... Thanks 
@mejta

**Comment by besrabasant** [comment]
just removing the item is not working

**Comment by mejta** [comment]
Bug is solved by https://github.com/roots/sage-woocommerce/pull/5

**Comment by arthurkirkosa** [comment]
I'm having the same problem with the latest version of this package and woo.

Is the @extends method fixed or it's still not recommended?

**Comment by mmirus** [comment]
Hey @arthurkirkosa - can you provide more detail on what you're trying to do, e.g., what template you're editing?

AFAIK the correct approach is still what @mejta indicated above:

> Have a look into the original template from WooCommerce plugin and if the original template doesn't contain `get_header` or `get_footer` function call, don't use `@extends` or `@section` in your template.

**Comment by arthurkirkosa** [comment]
With @mejta 's approach works.

Was wondering if that's the only way to do it. If so, I'm already doing it :)
